### ISSUE TITLE
Idea: Turn this from a fork to a consumer

### ISSUE THREAD

**Issue by grembo** [depenguin-me/depenguin-installer#4]
It might make sense to maintain this more as a consumer of mfsbsd instead of a fork. This would mean that we store custom configs and the scriptwork required to build the mfsbsd images here (probably locked to a specific upstream commit we can then adjust as we evolve with mfsbsd). This would allow to keep this very small and avoid constant merging/rebasing. It would also force us to get required changes in mfsbsd into upstream over time (while we can also patch locally to bridge gaps).

**Comment by bretton** [comment]
Using https://github.com/depenguin-me/depenguin-builder as consumer

**Comment by grembo** [comment]
Cool
